#!/bin/bash -e

shopt -s extglob
export LC_CTYPE=en_US.UTF-8
export LANG=en_US.UTF-8

PACKAGES=""
BUILD_MODES=""
BUILD_OPTIONS=""

RED=$(tput setaf 1)
GREEN=$(tput setaf 2)
YELLOW=$(tput setaf 3)
BLUE=$(tput setaf 4)
BOLD=$(tput bold)
ALL_OFF=$(tput sgr0)
readonly ALL_OFF BOLD BLUE GREEN RED YELLOW

plain() {
	local mesg=$1; shift
	printf "${BOLD}	${mesg}${ALL_OFF}\n" "$@" >&2
}

msg() {
	local mesg=$1; shift
	printf "${BOLD}${GREEN}==>${ALL_OFF}${BOLD} ${mesg}${ALL_OFF}\n" "$@" >&2
}

msg2() {
	local mesg=$1; shift
	printf "${BOLD}${BLUE}  ->${ALL_OFF}${BOLD} ${mesg}${ALL_OFF}\n" "$@" >&2
}

warning() {
	local mesg=$1; shift
	printf "${BOLD}${YELLOW}==> WARNING:${ALL_OFF}${BOLD} ${mesg}${ALL_OFF}\n" "$@" >&2
}

error() {
	local mesg=$1; shift
	printf "${BOLD}${RED}==> ERROR:${ALL_OFF}${BOLD} ${mesg}${ALL_OFF}\n" "$@" >&2
}

stat_busy() {
	local mesg=$1; shift
	printf "${BOLD}${GREEN}==>${ALL_OFF}${BOLD} ${mesg}...${ALL_OFF}" >&2
}

stat_done() {
	printf "${BOLD}done${ALL_OFF}\n" >&2
}

run_namcap() {
	local file=$1; shift
	msg2 "Linting ${file}..."
	namcap "${file}" \
		|sed -r "s|(.+) (W: .+)|     ${BOLD}${BLUE}\\1 ${YELLOW}\\2 ${ALL_OFF}|g" \
		|sed -r "s|(.+) (E: .+)|     ${BOLD}${BLUE}\\1 ${RED}\\2 ${ALL_OFF}|g"
}

sign() {
	local file=$1; shift
	msg2 "Signing ${file}..."
	gpg --pinentry-mode loopback --yes --detach-sign "${file}"
}

mksrcinfo() {
	stat_busy "Updating .SRCINFO"
	makepkg --printsrcinfo > .SRCINFO
	stat_done
}

# parse options
while [[ ${#} -gt 0 ]]; do
	key="${1}"
	case ${key} in
		--testing)
			TESTING_x86_64=1
			BUILD_MODES="${BUILD_MODES} testing-x86_64-build"
			PUBLISH_PACKAGES="testingpkg"
			PUBLISH_COMMUNITY="community-testingpkg"
		;;
		--testing-x86_64)
			TESTING_x86_64=1
			BUILD_MODES="${BUILD_MODES} testing-x86_64-build"
			PUBLISH_PACKAGES="testingpkg -a x86_64"
			PUBLISH_COMMUNITY="community-testingpkg -a x86_64"
		;;
		--staging)
			STAGING_x86_64=1
			BUILD_MODES="${BUILD_MODES} staging-x86_64-build"
			PUBLISH_PACKAGES="stagingpkg"
			PUBLISH_COMMUNITY="community-stagingpkg"
		;;
		--staging-x86_64)
			STAGING_x86_64=1
			BUILD_MODES="${BUILD_MODES} staging-x86_64-build"
			PUBLISH_PACKAGES="stagingpkg -a x86_64"
			PUBLISH_COMMUNITY="community-stagingpkg -a x86_64"
		;;
		--core)
			EXTRA_x86_64=1
			BUILD_MODES="${BUILD_MODES} extra-x86_64-build"
			PUBLISH_PACKAGES="corepkg"
			PUBLISH_COMMUNITY="communitypkg"
		;;
		--extra)
			EXTRA_x86_64=1
			BUILD_MODES="${BUILD_MODES} extra-x86_64-build"
			PUBLISH_PACKAGES="extrapkg"
			PUBLISH_COMMUNITY="communitypkg"
		;;
		--extra-x86_64)
			EXTRA_x86_64=1
			BUILD_MODES="${BUILD_MODES} extra-x86_64-build"
			PUBLISH_PACKAGES="extrapkg -a x86_64"
			PUBLISH_COMMUNITY="communitypkg -a x86_64"
		;;
		--multilib)
			MULTILIB=1
			BUILD_MODES="${BUILD_MODES} multilib-build"
			PUBLISH_PACKAGES="multilibpkg"
			PUBLISH_COMMUNITY="${PUBLISH_PACKAGES}"
		;;
		--multilib-staging)
			MULTILIB_STAGING=1
			BUILD_MODES="${BUILD_MODES} multilib-staging-build"
			PUBLISH_PACKAGES="multilib-stagingpkg"
			PUBLISH_COMMUNITY="${PUBLISH_PACKAGES}"
		;;
		--multilib-testing)
			MULTILIB_TESTING=1
			BUILD_MODES="${BUILD_MODES} multilib-testing-build"
			PUBLISH_PACKAGES="multilib-testingpkg"
			PUBLISH_COMMUNITY="${PUBLISH_PACKAGES}"
		;;
		-s|--nosig|--skip-sig)
			SKIP_SIG=1
		;;
		--nobuild|--skip-build)
			SKIP_BUILD=1
		;;
		--nosrc|--skip-src)
			SKIP_SRC=1
		;;
		--nodist|--skip-dist)
			SKIP_DIST=1
		;;
		--nolist|--skip-list)
			SKIP_LIST=1
		;;
		--nocheck|--skip-check)
			SKIP_CHECK=1
		;;
		--keepcheck)
			KEEP_CHECK_FILES=1
		;;
		-u|--updpkgsums)
			UPDATE_PKG_SUMS=1
		;;
		-c|--recreate|--clean)
			BUILD_OPTIONS="${BUILD_OPTIONS} -c"
		;;
		--bump)
			BUMP_PKGREL=1
		;;
		--rebuild)
			BUMP_PKGREL=1
			REBUILD=1
			STAGING_x86_64=1
			BUILD_MODES="${BUILD_MODES} staging-x86_64-build"
			PUBLISH_PACKAGES="stagingpkg"
			PUBLISH_COMMUNITY="community-stagingpkg"
		;;
		--rebuild-community)
			BUMP_PKGREL=1
			REBUILD_COMMUNITY=1
			STAGING_x86_64=1
			BUILD_MODES="${BUILD_MODES} staging-x86_64-build"
			PUBLISH_PACKAGES="stagingpkg"
			PUBLISH_COMMUNITY="community-stagingpkg"
		;;
		--rebuild-multilib)
			BUMP_PKGREL=1
			REBUILD_MULTILIB=1
			REBUILD_COMMUNITY=1
			MULTILIB_STAGING=1
			BUILD_MODES="${BUILD_MODES} multilib-staging-build"
			PUBLISH_PACKAGES="multilibpkg"
			PUBLISH_COMMUNITY="${PUBLISH_PACKAGES}"
		;;
		-p|--publish)
			PUBLISH=1
		;;
		-e|--edit)
			EDIT=1
		;;
		*)
			# TODO: accept non local package arguments when rebuilding
			if [ ! -f "${key}/PKGBUILD" ]; then
				error "unrecognized option '${key}'"
				exit 1
			fi
			PACKAGES="${PACKAGES} ${key}"
		;;
	esac
	shift
done

# default build mode settings
if [ -z "${BUILD_MODES}" ]; then
	EXTRA_x86_64=1
	BUILD_MODES="extra-x86_64-build"
	PUBLISH_PACKAGES="extrapkg"
	PUBLISH_COMMUNITY="communitypkg"
fi

# build packages
for PACKAGE in ${PACKAGES}; do
	msg "Building ${PACKAGE}..."
	pushd "${PACKAGE}" >/dev/null

	msg2 "Cleaning old files..."
	rm -f *.log

	# edit PKGBUILD
	if [ -n "${EDIT}" ]; then
		msg2 "Editing PKGBUILD..."
		${EDITOR} PKGBUILD
	fi

	# update pkgsums
	if [ -n "${UPDATE_PKG_SUMS}" ]; then
		msg2 "Updating package checksums..."
		updpkgsums
	fi

	# initial .SRCINFO update for package vars
	mksrcinfo
	archs=$(grep 'arch =' .SRCINFO|cut -d= -f2|cut -d' ' -f2|tr '\n' ' ')
	validpgpkeys=$(grep 'validpgpkeys =' .SRCINFO|cut -d= -f2|cut -d' ' -f2|tr '\n' ' ')
	pkgrel=$(grep 'pkgrel =' .SRCINFO|cut -d= -f2|cut -d' ' -f2|tr -d '\n')
	if [[ -n "${BUMP_PKGREL}" ]]; then
		let "pkgrel++"
		msg2 "Bumping pkgrel to ${pkgrel}"
		sed -r "s|(pkgrel=).+|\1${pkgrel}|g" -i PKGBUILD
	fi

	# import all needed gpg keys
	for validpgpkey in ${validpgpkeys}; do
		msg2 "Importing PGP key: ${validpgpkey}"
		gpg --recv-keys "${validpgpkey}" &>/dev/null
	done

	# build selected modes
	if [[ -z "${SKIP_BUILD}" ]]; then
		for BUILD_MODE in ${BUILD_MODES}; do
			# skip mode if not valid
			arch=$(echo ${BUILD_MODE}|sed -r 's|.+-(.+)-.+|\1|')
			if [[ ! "${BUILD_MODE}" == *"multilib"* && \
					! " ${archs[@]} " =~ ' any ' && \
					! " ${archs[@]} " =~ " $(echo ${BUILD_MODE}|sed -r 's|.+-(.+)-.+|\1|') " ]]; then
				continue
			fi
			msg "Building via ${BUILD_MODE} ${BUILD_OPTIONS}..."
			${BUILD_MODE} ${BUILD_OPTIONS}
		done
	fi

	# post build .SRCINFO for updated pkgver
	mksrcinfo
	pkgbase=$(grep 'pkgbase =' .SRCINFO|cut -d= -f2|cut -d' ' -f2|tr -d '\n')
	pkgname=$(grep 'pkgname =' .SRCINFO|cut -d= -f2|cut -d' ' -f2|tr '\n' ' ')
	pkgver=$(grep 'pkgver =' .SRCINFO|cut -d= -f2|cut -d' ' -f2|tr -d '\n')
	pkgrel=$(grep 'pkgrel =' .SRCINFO|cut -d= -f2|cut -d' ' -f2|tr -d '\n')
	epoch=$(grep 'epoch =' .SRCINFO|cut -d= -f2|cut -d' ' -f2|tr -d '\n')
	if [[ -n "${epoch}" ]]; then
		epoch="${epoch}:"
	fi
	pkgverfull="${epoch}${pkgver}-${pkgrel}"

	# create source tarball
	if [[ -z "${SKIP_SRC}" ]]; then
		stat_busy "Creating source tarball"
		extra-x86_64-build -- -- -S -d -f &>/dev/null
		rm -f '*-namcap.log'
		stat_done
	fi

	# signing tarballs
	tarballsrc="${pkgbase}-${pkgverfull}.src.tar.gz"
	if [ -z "${SKIP_SIG}" ]; then
		msg "Signing tarballs..."
		if [[ -f "${tarballsrc}" ]]; then
			sign "${tarballsrc}"
		fi
		for pkg in ${pkgname}; do
			for arch in ${archs}; do
				tarballpkg="${pkg}-${pkgverfull}-${arch}.pkg.tar.xz"
				sign "${tarballpkg}"
			done
		done
	else
		# remove signature files
		rm -f "${tarballsrc}.sig"
		for pkg in ${pkgname}; do
			for arch in ${archs}; do
				tarballpkg="${pkg}-${pkgverfull}-${arch}.pkg.tar.xz.sig"
				rm -f "${tarballpkg}"
			done
		done
	fi

	if [ -z "${SKIP_LIST}" ]; then
		msg "Listing package contents..."
		for pkg in ${pkgname}; do
			for arch in ${archs}; do
				tarballpkg="${pkg}-${pkgverfull}-${arch}.pkg.tar.xz"
				msg2 "Listing ${tarballpkg}..."
				for file in $(tar --force-local -tf "${tarballpkg}" 2>&1|grep -v 'SCHILY.fflags'|sort); do
					printf "${BOLD}${BLUE}	 %s${ALL_OFF}\n" "${file}" >&2
				done
			done
		done
	fi

	if [ -z "${SKIP_CHECK}" ]; then
		msg "Running namcap..."
		for pkg in ${pkgname}; do
			for arch in ${archs}; do
				tarballpkg="${pkg}-${pkgverfull}-${arch}.pkg.tar.xz"
				run_namcap "${tarballpkg}"
			done
		done
		run_namcap PKGBUILD
		msg "Running checkpkg..."
		checkpkg || true
		if [ -z "${KEEP_CHECK_FILES}" ]; then
			rm -rf /tmp/checkpkg-script.*
		fi
	fi
	msg "Finished building ${PACKAGE} ${pkgverfull}"

	# distribute into repo checkout
	if [[ -d "../.repo/packages/${pkgbase}/trunk" ]]; then
		repo='packages'
	else
		if [[ -d "../.repo/community/${pkgbase}/trunk" ]]; then
			repo='community'
		fi
	fi
	if [[ -z "${SKIP_DIST}" && -n "${repo}" ]]; then
		destdir="../.repo/${repo}/${pkgbase}/trunk"
		if [[ ! -f "${tarballsrc}" ]]; then
			warning "Skipping distribution: missing ${tarballsrc}"
		else
			msg "Distributing ${PACKAGE} ${pkgverfull} into ${repo}..."
			msg2 "Cleaning target..."
			rm -f "./${destdir}/"*
			msg2 "Extracting sources..."
			tar --force-local --strip-components=1 -xvf "${tarballsrc}" -C "./${destdir}" &>/dev/null
			rm "./${destdir}/.SRCINFO"
			msg2 "Creating symlinks..."
			for pkg in ${pkgname}; do
				for arch in ${archs}; do
					tarballpkg="${pkg}-${pkgverfull}-${arch}.pkg.tar.xz"
					ln -rs "${tarballpkg}"{,.sig} "${destdir}"
				done
			done

			# publish release
			if [[ "${PUBLISH}" -eq 1 ]]; then
				stat_busy "Confirm ${PACKAGE} ${pkgverfull} to publish"
				read
				git commit -v .
				pushd "${destdir}" >/dev/null
				if [[ 'packages' = "${repo}" ]]; then
					${PUBLISH_PACKAGES}
				elif [[ 'community' = "${repo}" ]]; then
					${PUBLISH_COMMUNITY}
				fi
				popd >/dev/null
			fi
		fi
	fi

	popd >/dev/null
done
